---
name: TestPlugin
author: JaxkDev
description: Testing............................
version: 1.1.1
api: [5.12.0]
main: JaxkDev\TestPlugin\Main
src-namespace-prefix: JaxkDev\TestPlugin

commands:
  Hello:
    description: "Hello command"
    permission: hello.command
    usage: /hello
    permission-message: "No Hello."
    aliases: ["hi"]
...
