---
name: TestPlugin
author: JaxkDev
description: Testing...........
version: 1.0.1
api: 3.10.0
main: JaxkDev\TestPlugin\Main

depend: ["Unknown Plugin", "Should work"]

commands:
  Hello:
    description: "Hello command"
    permission: hello.command
    usage: /hello
    permission-message: "No Hello."
    aliases: ["hi"]
...
