---
name: Testplugin
author: JaxkDev
description: Testing............................
version: 1.1.2
api: [3.0.0, 4.0.0, 5.2.0]
main: JaxkDev\TestPlugin\Main
src-namespace-prefix: JaxkDev\TestPlugin

commands:
  Hello:
    description: "Hello command"
    permission: hello.command
    usage: /hello
    permission-message: "No Hello."
    aliases: ["hi"]
...
