---
name: TestPlugin
author: JaxkDev
description: Testing..............
version: 1.0.1
api: 3.0.0
main: JaxkDev\TestPlugin\Main

depend: []
extensions: ["Extension1","Extension2","Extension3"]

commands:
  Hello:
    description: "Hello command"
    permission: hello.command
    usage: /hello
    permission-message: "No Hello."
    aliases: ["hi"]
...
