---
name: TestPlugin
author: JaxkDev
description: Testing............................
version: 1.1.0
api: [3.0.0, 3.1.1, 4.0.5, 5.0.0, 5.12.0]
main: JaxkDev\TestPlugin\Main
src-namespace-prefix: JaxkDev\TestPlugin

commands:
  Hello:
    description: "Hello command"
    permission: hello.command
    usage: /hello
    permission-message: "No Hello."
    aliases: ["hi"]
...
