---
name: TestPlugin
author: JaxkDev
description: Testing..............
version: 1.0.1
api: [4.0.0, 5.0.0, 6.0.0, 3.0.0, 3.11.2, 4.4.1]
main: JaxkDev\TestPlugin\Main
src-namespace-prefix: JaxkDev\TestPlugin

depend: []
extensions: ["Extension1","Extension2","Extension3"]

commands:
  Hello:
    description: "Hello command"
    permission: hello.command
    usage: /hello
    permission-message: "No Hello."
    aliases: ["hi"]
...
